### ISSUE TITLE
Notification not showing up after respringing while downloading

### ISSUE THREAD

**Issue by RuntimeOverflow** [lgariv/Prog#14]
(Minor issue and totally unimportant.) A new notification needs to be sent after a respring because every old one will be deleted.

**Comment by RuntimeOverflow** [comment]
@lgariv Should be fixed now! (Try it just to be sure.) And with that I guess my contribution is done for the initial release, if there are any further issues, just mention me here.

**Comment by lgariv** [comment]
Great work!
Looks to be somewhat buggy tho... look at those screenshots, after a respring:

![image](https://user-images.githubusercontent.com/5081484/104530435-9ee3dc80-5614-11eb-8545-0947e04ce925.jpeg)![image](https://user-images.githubusercontent.com/5081484/104530443-a30ffa00-5614-11eb-911e-e9698c0dc08f.jpeg)

Notification that already started to downloading before the respring, are not showing up.

**Comment by lgariv** [comment]
Correction:

Tried with bigger apps, and it seems like the progress bar notification does show up after a respring, but the install completed one does not persist through resprings. I'm not sure if this is a bug or intentional, but preferred behavior for the notification is to stay until either opened or cleared (The install phase itself could also occur _during_ a respring, resulting in no notification at all).

**Comment by RuntimeOverflow** [comment]
Ok so it is supposed to resend notifications with a progress bar when respringing mid-way through the download, but the notifications when the installation is done don‘t reappear, because there is no way to find out if there was a download complete notification before the respring. So if you wanted that, we would need another way to create push notification, so the system handles the resending of them.

**Comment by RuntimeOverflow** [comment]
@lgariv Just to be sure, the notification reappearing works for the progress bar (as intended)? But the install completed doesn't show up, which is intentional because I need to find another method of dispatching the notification.

**Comment by RuntimeOverflow** [comment]
I could probably come up with a solution to readd installed notifications, but I think there's no way to fix the issue if the install finishes during a respring, which is unfortunate but so rare that I think no one will care.

**Comment by lgariv** [comment]
> @lgariv Just to be sure, the notification reappearing works for the progress bar (as intended)? But the install completed doesn't show up, which is intentional because I need to find another method of dispatching the notification.

Yes, I believe so.

Can't it be solved the same way you solved the progress bar notification? Or maybe another static NSMutableDictionary, that contains bundle identifiers as keys and state (downloading / completed) as values?

**Comment by RuntimeOverflow** [comment]
No, because the progress bar notification gets created when the springboard finished loading and it looks for applications, which are currently installing, which isn't the case for finished applications but don't worry, I'm working on something.

**Comment by RuntimeOverflow** [comment]
@lgariv Can you try my new fix? If it works you can close the issue.

**Comment by lgariv** [comment]
@RuntimeOverflow After testing thoroughly, it works worse than before, unfortunately. Progress notifications won't be restored after respring, and finished notifications come back only after 2 resprings for some reason. 

I think it would be better to restore things to hire they were before (restoring progress notification only), until we figure it a fix for v1.1.0.

**Comment by RuntimeOverflow** [comment]
@lgariv I don't have any issues on my iPhone X iOS 13.5, so I have tried it on an iPhone 7 iOS 14.3 and I'm actually able to reproduce the issue. Let me try to fix it for a bit, if I don't find a solution, I'll revert the commit.

**Comment by RuntimeOverflow** [comment]
@lgariv I got the issue, my code works flawlessly, however, the problem is the Bulletins get dispatched too early, which (for some reason) causes them to not show up (and no, the BBServer isn't NULL at the time, it just doesn't work). My temporary fix is to use a dispatch_after, which of course heavily depends on how fast the BBServer is ready, however from the timing I used it works on iOS 14. The only worrying thing is that the minimum time I have to wait to get it consistent is higher than on iOS 13 meaning we should probably find a solution, as I cannot guarantee that it works on every device/iOS version.

**Comment by RuntimeOverflow** [comment]
e794e66

**Comment by lgariv** [comment]
@RuntimeOverflow I've been getting these consistently after every respring, even without installing anything
![image](https://user-images.githubusercontent.com/5081484/104921754-68a2b600-59a2-11eb-9e15-3821b7565acc.jpeg)

**Comment by RuntimeOverflow** [comment]
@lgariv "Even without installing anything", well that's not true. These notifications are still from the previous version of the tweak (I assume because there is no other explanation), just because they didn't show up, doesn't mean they don't exist. The fact that it shows (null) is definitely a bug, which also has the effect that you can't clear them (only temporary) and they show up after every respring. This likely happens because you have deleted the app before dismissing the notification (or you haven't dismissed the notification at all because it didn't show up). So I'll quickly push an update, but I guess it should work now (apart from the null notification).

**Comment by RuntimeOverflow** [comment]
It should finally be fixed now if it still doesn't work, I can't explain it anymore. a1afec0

**Comment by lgariv** [comment]
Seems to be working now
