### ISSUE TITLE
Progress Bar doesn't show up if you're on the NC while the notification appears.

### ISSUE THREAD

**Issue by RuntimeOverflow** [lgariv/Prog#15]
Leaving and reentering the NC will fix it.

**Comment by RuntimeOverflow** [comment]
@lgariv Does not seem to be fixed.

**Comment by RuntimeOverflow** [comment]
Nope, still happens.

**Comment by lgariv** [comment]
@RuntimeOverflow Please consider the "Assignees" next time, I already assigned it to myself and had a working fix in my local repo. Anyway, glad you got it fixed.

**Comment by RuntimeOverflow** [comment]
@lgariv Oh sorry, I thought you were done with it (and thought it was fixed) because you created another commit (9c25466).
