### ISSUE TITLE
Question regarding notification names

### ISSUE THREAD

**Issue by RuntimeOverflow** [lgariv/Prog#20]
@lgariv There are two types of display names for each app, the AppStore display name, and the actual app name. For most apps, this may be the same, but for this example, I'll take Twitch. In the AppStore, it's called: "Twitch: Live Game Streaming", while on the home screen it's just called: "Twitch". Now the question is, which one do we want to use for our notifications. For consistency, I would recommend using the app name "Twitch", because every other notification also shows Twitch, but it is up to you to decide. I used `[[%c(SBApplicationController) sharedInstance] applicationWithBundleIdentifier:self.bundleIdentifier].displayName` (Twitch), while you replaced it in commit f63a15c with `self.displayName` (Twitch: Live Game Streaming). It may be intentional by you, or you thought you could optimize the code (I just want to be sure that you are aware of it). Could you give me a definitive answer to which one you want?

**Comment by lgariv** [comment]
I did not know about that difference; I replaced your line because it did not work on my device, so I thought it was a bug. If it was working for you, then it is probably an iOS 14 compatibility problem.

**Comment by RuntimeOverflow** [comment]
@lgariv Now that I think about it, this could be another issue with the fact that it only works when updating and not when installing, because I use SBApplication, which may not exist on a new install.

**Comment by lgariv** [comment]
> @lgariv Now that I think about it, this could be another issue with the fact that it only works when updating and not when installing, because I use SBApplication, which may not exist on a new install.

That makes sense. If you find any other way to get the other kind of display name, go ahead. I don't really prefer one over the other, so it is not a priority.
