### ISSUE TITLE
NCNotificationLongLookView does not dismiss after tapping on an action.

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#22]

**Comment by RuntimeOverflow** [comment]
@lgariv I'll try this one if you don't work on it. Should it only dismiss certain actions or all of them?

**Comment by RuntimeOverflow** [comment]
14aaeae

**Comment by lgariv** [comment]
@RuntimeOverflow [Still not dismissing](https://streamable.com/hf73li) the LongLook view after tapping. The expected behavior when tapping on an action should be the same as tapping on the blurred background.

Also, in the video you can see that if tapping on prioritize when paused, the resume action gets stuck. I think it could be fixed just by calling `resumeWithResult:` in the first line (before `%orig;`) inside `prioritizeWithResult:`.

**Comment by RuntimeOverflow** [comment]
@lgariv Yet another iOS 14 issue, but fixed now b807307.
