### ISSUE TITLE
Any reason for GO_EASY_ON_ME?

### ISSUE THREAD

**Issue by RuntimeOverflow** [lgariv/Prog#23]
It's generally bad practice to use because it suppresses warnings. And seeing as our code compiles fine without it, I recommend to remove it, unless there's a good reason to use it. And even if there will be an unavoidable warning, it can be suppressed using `#pragma clang diagnostic ignored`, which has the advantage of only suppressing one given warning inside the block.

**Comment by lgariv** [comment]
I use it mainly to suppress “unused variable” and things like that while debugging a local build, feel free to remove it if you want to

**Comment by RuntimeOverflow** [comment]
@lgariv Here's a quick tip (I don't know if you already know it): You can add this line in your code somewhere: `(void)myVariable;` It makes the compiler think the variable is used.
