### ISSUE TITLE
Replace notification date with completed percentage

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#26]
(Should be applied to progress notification only)

**Comment by lgariv** [comment]
@RuntimeOverflow I looked into it and couldn't get it to work without hooking the wrong notifications again, can you try this one? probably not that complicated.

**Comment by RuntimeOverflow** [comment]
Sure I held back because you assigned it to yourself, but I'll do it.

**Comment by RuntimeOverflow** [comment]
Implemented. (b4f40ed)

**Comment by RuntimeOverflow** [comment]
Nope, still issues.

**Comment by RuntimeOverflow** [comment]
@lgariv Seeing as you worked on this, have you got any prototype working? For me, it keeps crashing when trying to add a KVO observer to the progress.

**Comment by RuntimeOverflow** [comment]
Implemented & Fixed. (ae8a7ba)

**Comment by lgariv** [comment]
@RuntimeOverflow Looks like there's some inconsistency there. Happened while trying to update a few apps. 
![image](https://user-images.githubusercontent.com/5081484/108609689-4c969800-73d8-11eb-9fb3-d65f2c0a44dd.png)
