### ISSUE TITLE
Big notification view size on bigger font sizes

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#28]
Might be possible to side by removing text altogether from the notification body in another step, and tag the view from there.

Might be a good idea to hook the NCNotificationShortLookViewController and NCNotificationLongLookViewController `viewWillLoad:` method for that purpose.

**Comment by RuntimeOverflow** [comment]
@lgariv Not sure if I understand the issue, but I assume you mean that with a larger font size, the default notifications content of "com.miwix.downloadbar14-progressbar" will wrap, thus making a second line appear which makes the notification body larger? If that is what you mean, it's fixed now and you can close the issue.
