### ISSUE TITLE
Modifying wrong notification views

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#4]
![image](https://user-images.githubusercontent.com/5081484/103630100-e1892300-4f49-11eb-84b5-2229e6888510.jpeg)

**Comment by RuntimeOverflow** [comment]
Hmm, I thought I fixed this issue, will look into it. Probably due to view reusability.

**Comment by lgariv** [comment]
> Hmm, I thought I fixed this issue, will look into it. Probably due to view reusability.

Probably, yes... Notification views are managed horribly as far as I'm aware. Of course it is a non-issue for Apple as this is a private framework🤷‍♂️

It is probably tied to the contents of the NCNotificationShortLookView being added as a part of layoutSubviews, and each of these have their own layoutSubviews running at the same time. With multiple notifications and reusable views, it can be tricky to avoid this bug.

I'm no expert on how this works, so not sure if I got it right... but that's what I'd check first.

**Comment by RuntimeOverflow** [comment]
I don't think it's hard, every time a notification gets reused, it will be readded to the list, which will call the didMoveToSuperview function, where we can reset our view.

**Comment by RuntimeOverflow** [comment]
@lgariv Does this happen with my version or your version? Because I really thought I fixed this and I'm unable to reproduce this issue on my device anymore, even though I had it before.

**Comment by lgariv** [comment]
> I don't think it's hard, every time a notification gets reused, it will be readded to the list, which will call the didMoveToSuperview function, where we can reset our view.

At least for notification contents, layoutSubviews is executed every time it "appears".

For example: if you have a long notification list, then scrolled down - which will get some notifications out of sight - and scroll back up to reveal them again they will perform layoutSubviews (even if they were loaded before).

> @lgariv Does this happen with my version or your version? Because I really thought I fixed this and I'm unable to reproduce this issue on my device anymore, even though I had it before.

@RuntimeOverflow The problem happens when you have a lot of notifications, and especially if you scroll fast between them. Try not to clear you notifications for a while and check again.

(I have an idea for a quick fix, but it might just happen less instead of not at all.)

**Comment by RuntimeOverflow** [comment]
I guess you need to fix it because I really can't reproduce this at all.

**Comment by RuntimeOverflow** [comment]
Fixed (See Pull Request #10)
