### ISSUE TITLE
Dismissing one notification dismiss all of them

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#5]
When downloading multiple apps, the user get multiple notifications (as expected); however, when dismissing one of them, all of the other (DownloadBar14) notifications dismiss as well.

**Comment by RuntimeOverflow** [comment]
Noticed that too, probably because the notifications are somehow connected (they have the same *ID).

**Comment by lgariv** [comment]
I think that as well. Shouldn't be too hard to fix, just didn't have time to try yet.

**Comment by RuntimeOverflow** [comment]
Might be harder than anticipated. I tried changing almost all variables ending in ID. The only one which fixed it is the sectionID, which we can't change because that's the app that publishes the notifications (In our case: com.apple.Preferences).
