### ISSUE TITLE
Applying notification hooks to NCNotificationLongLookView

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#6]
To show the progress view when Haptic/3D Touch-ing on the notification.

Note: this is more than duplicating the code and hooking NCNotificationLongLookView instead - doing so will result in having 2 different UIProgressView instances, that aren't in sync with each other and is basically inefficient. This requires using the same view, which means we might have to re-implement adding the UIProgressView to the appropriate view.

**Comment by RuntimeOverflow** [comment]
Implemented. (See Pull Request #9)
