### ISSUE TITLE
Determine when updating vs. installing, and install phase

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#7]
* To post (and update dynamically) the correct bulletin title.

* To remove "Pause" and "Resume" actions from notification when in the install phase.

**Comment by lgariv** [comment]
@RuntimeOverflow Couldn't find the appropriate property/method for this one, can you take a look into it?

**Comment by RuntimeOverflow** [comment]
Implemented. (4df1289 & 9e9624a)

**Comment by lgariv** [comment]
Testing in a few hours, looks good

**Comment by lgariv** [comment]
After doing some testing, it doesn't appear to be working on iOS 14 (at least for me). Always states that it is downloading (all apps in this screenshot are updates):
![image](https://user-images.githubusercontent.com/5081484/108609733-a13a1300-73d8-11eb-97cd-a9089bef4d06.png)

**Comment by lgariv** [comment]
Update: seems like an `ldrestart` fixed that, for some reason. I'll keep an eye on it in the next few days.
