### ISSUE TITLE
Pin notification to the top

### ISSUE THREAD

**Issue by lgariv** [lgariv/Prog#8]
Should behave exactly as the "Do Not Disturb" notification.

**Comment by lgariv** [comment]
@RuntimeOverflow Have you tried to figure out how we can do that? I'm sure there's a way to do it, but so far I've found nothing.

**Comment by RuntimeOverflow** [comment]
@lgariv I have looked into it, but without success. You tried the lockscreenPriority (or something like that), which didn't work and I tried to hook the BBBulletin's prioritizeAtTop getter, it does however, only pin it to the top of the older notifications. While it is progress, you still have to scroll down to see it. I'll be back in 2 hours and I can work on that if you don't find a solution until then.

**Comment by lgariv** [comment]
> @lgariv I have looked into it, but without success. You tried the lockscreenPriority (or something like that), which didn't work and I tried to hook the BBBulletin's prioritizeAtTop getter, it does however, only pin it to the top of the older notifications. While it is progress, you still have to scroll down to see it. I'll be back in 2 hours and I can work on that if you don't find a solution until then.

@RuntimeOverflow Have you tried hooking it with the destination set to the lockscreen instead of Notification Center? (I don't remember which one is lockscreen only)

**Comment by RuntimeOverflow** [comment]
@lgariv You're a genius, I have never thought of that. Looking at the DND banner, it gets sent to the Lockscreen and Coversheet (not NC). I'll look at it now.
